// ESTE ARQUIVO É ONDE CONSTAM AS VARIAVEIS DE AMBIENTE DO PROJETO.
// COMO EU NÃO QUERIA USAR UM ARQUIVO .env EU PREFERI CIRAR UM ARQUIVO
// JAVASCRIPT ONDE EU POSSO EXPORTAR AS URLS QUE VOU USAR DURANTE O PROJETO


// URLS DE ACESSO AO MONGO DB
// ALUNOS
exports.MONGO_URL = 'localhost:1111/controle-estudante';

// DISCIPLINAS
// exports.DISCIPLINAS_MONGO_URL = 'localhost:1111/disciplinas';